### ISSUE TITLE
Add structured data support to the "Team" post type

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx-team#6]
Add in the Schema data to the LSX Teams Plugin. Schema nodes used:

**Complete**
`jobTitle` ( the role taxonomy)
`worksFor` (Yoast Organization Fields)
`memberOf` (Yoast Organization Fields)
`email` (custom field)
`telephone` (custom field)
`connections` (connected projects and testimonials)

[LSX Demo](https://lsx-demo.lsdev.biz/team/ashley-shaw/)
[Google Structure Tool](https://search.google.com/structured-data/testing-tool/u/0/?utm_campaign=devsite&utm_medium=jsonld&utm_source=review-snippet#url=https%3A%2F%2Flsx-demo.lsdev.biz%2Fteam%2Fashley-shaw%2F)

**Comment by krugazul** [comment]
@ashleyshaw I have merged the the Schema branch, there is a demo link in the first comment.  I besides the usual title and description fields, these have been added in.

`jobTitle` -> (custom field)
`email` -> (custom field)
`telephone` -> (custom field)
`worksFor` -> Yoast Organization Setting
`memberOf` -> Yoast Organization Setting

**Comment by ashleyshaw** [comment]
@jacquesvdhorst  please add a clear description for this issue, I don't know what development you and @krugazul have completed.
