### ISSUE TITLE
LSX team is not loading the Slick JS.

### ISSUE THREAD

**Issue by joseabreu1985** [lightspeeddevelopment/lsx-team#8]
**Describe the bug**
Carousel is not working for team shortcode, The slickslider JS is not loading the necessary classes for the carousel to work. It seems that is conflicting with other scripts.

Note: The live version has the lsx team version 1.1.2 if we update this to 1.2.1 the slider crash and go to the left side of the screen and transform into a column too. 

**To Reproduce**
Steps to reproduce the behaviour:

Please check the lsdev live site https://www.lsdev.biz/services/woocommerce/

**Expected behaviour**
You will see the team section members on a column instead of a carousel as expected.

**Screenshots**

This is how it looks with the error (lsdev Live site).
<img width="1273" alt="live-error" src="https://user-images.githubusercontent.com/20842182/69179556-7e8cc080-0aea-11ea-8a57-1ddbe919f499.png">

This is how the slider should work(lsdev Dev site).
<img width="1275" alt="dev-correct-view" src="https://user-images.githubusercontent.com/20842182/69179582-89dfec00-0aea-11ea-82f7-60783fae067d.png">

**Desktop (please complete the following information):**

Happening in all browsers.

**Mobile (please complete the following information):**

Happening in device

**Comment by viscosho** [comment]
Closing, the root of this issue is flagged here: https://github.com/lightspeeddevelopment/lsx/issues/240
