### ISSUE TITLE
Thumbnails size is not correct on search results.

### ISSUE THREAD

**Issue by joseabreu1985** [lightspeeddevelopment/lsx-team#9]
**Describe the bug**
Thumbnails size is not correct on search results, They are taller than the others. This errors still happening after the usage of the thumbnails regenerator plugin.

**To Reproduce**
Steps to reproduce the behaviour:

Please check the lsdev live site (https://www.lsdev.biz/search/wordpress?fwp_paged=4) and dev site (https://lsdev-2019.feedmybeta.com/search/wordpress?fwp_paged=4) Go to the search bar and look for the keyword "wordpress" and then go to page results 4 to see that the thumbails are taller than the others.

**Expected behaviour**
The thumbnails size should be the same as the others search results (for example: post, project, etc).

**Screenshots**

Dev site with plugin version 1.2.1(recently)
<img width="1274" alt="dev-site-plugin-v-1 2 1" src="https://user-images.githubusercontent.com/20842182/69181653-3d96ab00-0aee-11ea-84d8-b7813585346c.png">

Live site with plugin version 1.1.2
<img width="1274" alt="live-site-plugin-v-1 1 2" src="https://user-images.githubusercontent.com/20842182/69181670-45eee600-0aee-11ea-851c-f3977d0800ad.png">

**Desktop (please complete the following information):**

Happening in all browsers.

**Mobile (please complete the following information):**

Happening in device.

**Comment by viscosho** [comment]
This fix is being tested in this branch https://github.com/lightspeeddevelopment/lsx/tree/thumbnail-fix
